### ISSUE TITLE
Local workspace file ('angular.json') could not be found.

### ISSUE THREAD

**Issue by jyotiranjan360** [mosh-hamedani/angular2-course#19]
E:\Project>ng serve
Local workspace file ('angular.json') could not be found.
Error: Local workspace file ('angular.json') could not be found. at WorkspaceLoader._getProjectWorkspaceFilePath (C:\Users\Bapi\AppData\Roaming\npm\node_modules\@angular\cli\models\workspace-loader.js:37:19)
    at WorkspaceLoader.loadWorkspace (C:\Users\Bapi\AppData\Roaming\npm\node_modules\@angular\cli\models\workspace-loader.js:24:21)
    at ServeCommand._loadWorkspaceAndArchitect (C:\Users\Bapi\AppData\Roaming\npm\node_modules\@angular\cli\models\architect-command.js:180:32)
    at ServeCommand.<anonymous> (C:\Users\Bapi\AppData\Roaming\npm\node_modules\@angular\cli\models\architect-command.js:47:25)
    at Generator.next (<anonymous>)
    at C:\Users\Bapi\AppData\Roaming\npm\node_modules\@angular\cli\models\architect-command.js:7:71
    at new Promise (<anonymous>)
    at __awaiter (C:\Users\Bapi\AppData\Roaming\npm\node_modules\@angular\cli\models\architect-command.js:3:12)
    at ServeCommand.initialize (C:\Users\Bapi\AppData\Roaming\npm\node_modules\@angular\cli\models\architect-command.js:46:16)
    at Object.<anonymous> (C:\Users\Bapi\AppData\Roaming\npm\node_modules\@angular\cli\models\command-runner.js:87:23)

**Comment by molcik** [comment]
It’s probably because your global **@angular/cli** version and **@angular/compiler-cli** are differentf  **[here is how to fix it](https://filipmolcik.com/error-local-workspace-file-angular-json-could-not-be-found/)**.
